#
# docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest . -f ./docker/rom-ldap/Dockerfile
# docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest
#
# image: 'ruby:2.3'

image : registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest

before_script:
  - bundle install


# Rubocop report.
#
rubocop:
  script:
    - rubocop

# Run specs and leave SimpleCov output.
#
# cd ./docker/apacheds
# docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest .
# docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
# gitlab-runner exec docker rspec
# gitlab-runner exec docker --docker-volumes /Users/pdh/.ssh/pdh:/root/.ssh/id_rsa:ro
# cd ./../..
#
rspec:
  variables:
    LDAPURI:    ldap://directory:10389
    LDAPBINDDN: uid=admin,ou=system
    LDAPBINDPW: secret
    # LDAPBASE:   ou=specs,dc=rom,dc=ldap
  services:
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
      alias: directory
  script:
    # - bundle install
    - ulimit -n 1024
    - rake # rspec
  artifacts:
    paths:
      - coverage/

# Publish spec coverage for the master branch.
#
pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
