image: ruby:2.4.5-alpine3.8

cache:
  paths:
    - vendor/ruby

test:
  variables:
    LDAPHOST:   apacheds
    LDAPBASE:   dc=rom,dc=ldap
    LDAPPORT:   '10389'
    LDAPBINDDN: uid=admin,ou=system
    LDAPBINDPW: secret
    LDAPDIR:    ${CI_PROJECT_DIR}/docker/schema

  services:
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:2.0.0-M24
      alias: apacheds
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389ds:latest
      alias: 389ds
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:latest
      alias: opendj
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:latest
      alias: openldap
    # - opendirectory
    # - activedirectory



  script:
    - apk upgrade --no-cache
    - apk add --no-cache build-base libxml2-dev openldap-clients git
    - gem install bundler --no-document
    - bundle install
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake ldap:modify
    - bundle exec rake
  artifacts:
    paths:
      - coverage/


pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - deploy
