
# stages:
#   - build
#   - test
#   - deploy


# image: ruby:2.4.5
# image: ruby:2.5.5
# image: ruby:2.6.2


#
# docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest . -f ./docker/rom-ldap/Dockerfile
# docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest
#
image: ruby:2.4

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - bundle install


# Run specs and leave SimpleCov output.
#
# $ cd ./docker/apacheds
#
# $ docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest .
#
# $ docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
#
# $ gitlab-runner exec docker test
#
# $ gitlab-runner exec docker --docker-volumes /Users/pdh/.ssh/pdh:/root/.ssh/id_rsa:ro
#
test:
  variables:
    # SSH_PRIVATE_KEY:
    LDAPURI:    ldap://directory:10389/ou=specs,dc=rom,dc=ldap
    LDAPBINDDN: uid=admin,ou=system
    LDAPBINDPW: secret

  services:
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
      alias: directory
    #   alias: apacheds
    # - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389:latest
    #   alias: 389
    # - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:latest
    #   alias: opendj
    # - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:latest
    #   alias: openldap
  script:
    # - bundle install
    - ulimit -n 1024
    - rake # rspec
  artifacts:
    paths:
      - coverage/




# Publish spec coverage for the master branch.
#
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
