cache:
  key: $CI_PROJECT_NAME
  paths:
    - vendor/ruby
    - vendor/cache

services:
  - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389ds:1.3.10.2
    alias: 389ds
  - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:2.0.0-M24
    alias: apacheds
  - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:4.4.9
    alias: opendj
  - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:2.4.57
    alias: openldap

# variables:
#   LDAPDIR: ${CI_PROJECT_DIR}/spec/fixtures/ldif

before_script:
  - apk upgrade --no-cache
  - apk add --no-cache build-base libxml2-dev
  - gem install bundler --no-document
  - bundle config set path vendor
  - bundle install -j $(nproc)

test-2.4:
  # inherit:
  #   default: true
  #   variables: true
  image: ruby:2.4-alpine
  script: bundle exec rspec --fail-fast

# test-2.5:
#   image: ruby:2.5-alpine
#   script: bundle exec rspec --fail-fast

# test-2.6:
#   image: ruby:2.6-alpine
#   script: bundle exec rspec --fail-fast

# test-2.7:
#   image: ruby:2.7-alpine
#   script: bundle exec rspec --fail-fast

# test-3.0:
#   image: ruby:3.0-alpine
#   script: bundle exec rspec --fail-fast




