
# stages:
#   - build
#   - test
#   - deploy


#
# docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest . -f ./docker/rom-ldap/Dockerfile
# docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest
#
image: ruby:2.4.5
# image: ruby:2.5.5
# image: ruby:2.6.2

test:
  variables:
    LDAPURI:    ldap://apacheds:10389/ou=specs,dc=rom,dc=ldap
    LDAPBINDDN: uid=admin,ou=system
    LDAPBINDPW: secret

  services:
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
      alias: apacheds
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389:latest
      alias: 389
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:latest
      alias: opendj
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:latest
      alias: openldap
  script:
    - bundle install --without development benchmark
    - ulimit -n 1024
    - rake
  artifacts:
    paths:
      - coverage/




# Publish spec coverage for the master branch.
#
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
