
# stages:
#   - build
#   - test
#   - deploy


#
# docker build -t registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest . -f ./docker/rom-ldap/Dockerfile
# docker push registry.gitlab.com/peterdavidhamilton/rom-ldap/rom-ldap:latest
#
image: ruby:2.4.5-alpine3.8

# before_script:
#   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $registry


# gitlab-runner exec docker test --docker-pull-policy never
test:
  variables:
    LDAPHOST:   apacheds
    LDAPBASE:   dc=rom,dc=ldap
    LDAPPORT:   '10389'
    LDAPBINDDN: uid=admin,ou=system
    LDAPBINDPW: secret
    LDAPDIR:    ${CI_PROJECT_DIR}/docker/schema

  services:
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:latest
      alias: apacheds
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389:latest
      alias: '389'
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:latest
      alias: opendj
    - name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:latest
      alias: openldap
    # - opendirectory
    # - activedirectory



  script:
    - apk upgrade --no-cache
    - apk add --no-cache build-base libxml2-dev openldap-clients git
    - gem install bundler --no-document
    - bundle install
    - bundle exec rake ldap:modify
    - rake
  artifacts:
    paths:
      - coverage/
      # - tmp/




# Publish spec coverage for the master branch.
#
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
