# rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - lib/**/*
    - rakelib/*
  Exclude:
    - doc/**/*
    - examples/**/*
    - log/*
    - spec/**/*.rb
    - spec/**/*.gemspec
    - vendor/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5

Style/LambdaCall:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  Enabled: false
