# rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Include:
    - Rakefile
    - lib/rom/**/*.rb
    - rakelib/*.rake
  Exclude:
    - '**/.*'
    - doc/**/*
    - docker/**/*
    - log/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'lib/rom-ldap.rb'

Style/SymbolProc:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Style/FrozenStringLiteralComment:
  # EnforcedStyle: always
  Enabled: false

