inherit_from: .rubocop_todo.yml
require: rubocop-performance
require: rubocop-rake
require: rubocop-rspec

AllCops:
  Include:
    - lib/rom/**/*.rb
  Exclude:
    - '**/.*'
    - doc/**/*
    - docker/**/*
    - log/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'lib/rom-ldap.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/SymbolProc:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
