# rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Include:
    - Rakefile
    - lib/**/*.rb
    - rakelib/*.rake
  Exclude:
    - '**/.DS_Store' # Lint/Syntax: Invalid byte sequence in utf-8.
    - doc/**/*
    - docker/**/*
    - log/*
    - spec/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'lib/rom-ldap.rb'

# Style/LambdaCall:
#   Enabled: false

# Metrics/LineLength:
#   Enabled: false

# Style/Encoding:
#   Enabled: true

# Style/FrozenStringLiteralComment:
#   EnforcedStyle: when_needed
#   Enabled: false
