# rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  Include:
    - Rakefile
    - lib/rom/**/*.rb
    - rakelib/*.rake
  Exclude:
    - '**/.*'
    - doc/**/*
    - docker/**/*
    - log/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'lib/rom-ldap.rb'

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/SymbolProc:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

# Style/FrozenStringLiteralComment:
#   Enabled: true
#   EnforcedStyle: always

