# rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - lib/**/*
    - rakelib/*
  Exclude:
    - '**/.DS_Store' # Lint/Syntax: Invalid byte sequence in utf-8.
    - doc/**/*
    - examples/**/*
    - log/*
    - spec/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

Style/LambdaCall:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  Enabled: false
