image: ruby:2.4.5-alpine3.8
pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - apk upgrade --no-cache
          - apk add --no-cache build-base libxml2-dev
          - gem install bundler --no-document
          - bundle config set path vendor
          - bundle install -j $(nproc)
          - bundle exec rspec
        services:
          - apacheds
          - 389ds
          - openldap
          - opendj

definitions:
  caches:
    bundler: ./vendor

  services:
    apacheds:
      memory: 512
      image:
        name: registry.gitlab.com/peterdavidhamilton/rom-ldap/apacheds:2.0.0-M24
        username: peterdavidhamilton
        password: $GITLAB_TOKEN

    389ds:
      memory: 512
      image:
        name: registry.gitlab.com/peterdavidhamilton/rom-ldap/389ds:1.3.8.4
        username: peterdavidhamilton
        password: $GITLAB_TOKEN

    openldap:
      memory: 512
      image:
        name: registry.gitlab.com/peterdavidhamilton/rom-ldap/openldap:2.4.48
        username: peterdavidhamilton
        password: $GITLAB_TOKEN

    opendj:
      memory: 512
      image:
        name: registry.gitlab.com/peterdavidhamilton/rom-ldap/opendj:4.4.3
        username: peterdavidhamilton
        password: $GITLAB_TOKEN
