version: '2.4'

networks:
  rom-ldap-network:


services:

  # docker attach rom-ldap
  rom:
    container_name: rom-ldap
    mem_limit: 6g
    mem_reservation: 2g
    build:
      context: ..
      dockerfile: docker/rom-ldap/Dockerfile
      labels:
        name: ROM LDAP Adapter
    environment:
      LDAPHOST: apacheds
      LDAPPORT: 10389
      LDAPBASE: dc=rom,dc=ldap
      LDAPBINDDN: uid=admin,ou=system
      LDAPBINDPW: secret
    restart: on-failure
    # entrypoint: bundle exec rake spec
    # entrypoint: ./bin/console
    volumes:
      - ../log:/src/log:rw
    healthcheck:
      test: ldapsearch -H ldap://apacheds:10389 -x
      interval: 1m30s
      timeout: 10s
      retries: 3
    tty: true
    stdin_open: true
    depends_on:
      - 389ds
      - apacheds
      - opendj
      - openldap
    networks:
      - rom-ldap-network



  # 1 ubuntu
  # docker build -t apacheds .
  # docker run -it -p 1389:10389 -e APACHEDS_INSTANCE=rom apacheds
  # ou=schema
  #
  apacheds:
    container_name: apacheds
    mem_limit: 6g
    mem_reservation: 4g
    build:
      context: ./apacheds
      labels:
        vendor: Apache
      args:
        # version: 2.0.0.AM25
        version: 2.0.0-M24
        repo: archive.apache.org
        architecture: amd64
    tty: true
    stdin_open: true
    ports:
      - 1389:10389
      - 1636:10636
    volumes:
      - ../log:/var/lib/apacheds/log:rw
    hostname: rom.ldap
    restart: on-failure
    environment:
      APACHEDS_INSTANCE: rom
    networks:
      - rom-ldap-network



  # 2 debian
  # docker build -t openldap .
  # docker run -it -p 2389:389 -e LDAP_DOMAIN=rom.ldap -e LDAP_BASE_DN=dc=rom,dc=ldap openldap
  #
  openldap:
    container_name: openldap
    build:
      context: ./openldap
      labels:
        vendor: OpenLDAP
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
    ports:
      - 2389:389
      - 2636:636
    hostname: rom.ldap
    restart: on-failure
    environment:
      # LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: ROM-LDAP OpenLDAP Server
      LDAP_DOMAIN: rom.ldap
      LDAP_BASE_DN: dc=rom,dc=ldap
      LDAP_ADMIN_PASSWORD: topsecret
    networks:
      - rom-ldap-network



  # 3 centos
  # cd ./389ds && docker build -t 389ds .
  # docker run -it -p 3389:389 -e DIRSRV_FQDN=rom.ldap -e DIRSRV_SUFFIX=dc=rom,dc=ldap 389
  # cn=schema
  #
  389ds:
    container_name: 389ds
    build:
      context: ./389ds
      labels:
        vendor: 389ds
    tty: true
    stdin_open: true
    ports:
      - 3389:389
      - 3636:636
      # - 9830:9830
    volumes:
      - /etc/dirsrv
      - /var/lib/dirsrv
      - ../log:/var/log/dirsrv:rw
      # - /var/log/dirsrv
    hostname: rom.ldap
    restart: on-failure
    environment:
      LDAP_LOG_LEVEL: 0
      DIRSRV_ID: rom
      DIRSRV_FQDN: rom.ldap
      DIRSRV_SUFFIX: dc=rom,dc=ldap
      DIRSRV_ROOT_DN: cn=Directory Manager
      DIRSRV_ROOT_DN_PASSWORD: topsecret
      # DIRSRV_ADMIN_USERNAME: admin
      # DIRSRV_ADMIN_PASSWORD: adminpassword
    networks:
      - rom-ldap-network




  # 4 debian
  # docker build -t opendj .
  # docker run -it -p 4389:389 -e BASE_DN=dc=rom,dc=ldap opendj
  #
  opendj:
    container_name: opendj
    build:
      context: ./opendj
      args:
        version: 4.3.1
      labels:
        vendor: OpenIdentity
    tty: true
    stdin_open: true
    ports:
      - 4389:389
      - 4636:636
      # - 4444:4444
    volumes:
      - /opt/opendj
    hostname: rom.ldap
    restart: on-failure
    environment:
      BASE_DN: dc=rom,dc=ldap
      ROOT_USER_DN: cn=Directory Manager
      ROOT_PASSWORD: topsecret
    networks:
      - rom-ldap-network
