---
version: '3.3'
networks:
  rom-ldap-network:

services:
  rom:
    container_name: rom-ldap
    build:
      context: ..
      dockerfile: docker/rom-ldap/Dockerfile
      args:
        version: 2.4
      labels:
        name: ROM LDAP Adapter
    # environment:
    #   - AD_URI
    #   - AD_USER
    #   - AD_PW
    #   - GITLAB_TOKEN
    #   - DEBUG
    #   - LDAPDIR=/src/spec/fixtures/ldif
    #   - DEFAULT_VENDOR=open_dj
    restart: on-failure
    depends_on:
      - apacheds
      - openldap
      - 389ds
      - opendj
    volumes:
      - ..:/src
      - ../tmp/bundler:/bundle
    tty: true
    stdin_open: true
    networks:
      - rom-ldap-network



  apacheds:
    container_name: apacheds
    build:
      context: ./apacheds
      args:
        instance: rom
        version: 2.0.0-M24 # tested against -M24
      labels:
        vendor: apache_ds
    tty: true
    stdin_open: true
    ports:
      - 1389:10389
      - 1636:10636
    restart: on-failure
    healthcheck:
      test: "curl ldap://127.0.0.1:10389/dc=rom,dc=ldap || exit 1"
    networks:
      - rom-ldap-network



  # $ docker exec -it openldap slapd -V
  #   2.4.57
  #
  openldap:
    container_name: openldap
    build:
      context: ./openldap
      args:
        instance: rom
      labels:
        vendor: open_ldap
    tty: true
    stdin_open: true
    ports:
      - 2389:389
      - 2636:636
    volumes:
      - ../tmp/openldap:/var/run # ldapi://socket
    restart: on-failure
    healthcheck:
      test: "curl -u 'cn=admin,dc=rom,dc=ldap:topsecret' ldap://127.0.0.1/dc=rom,dc=ldap || exit 1"
    networks:
      - rom-ldap-network



  # $ docker exec -it 389ds ns-slapd -v
  #   1.3.10.2
  #
  389ds:
    container_name: 389ds
    build:
      context: ./389ds
      args:
        instance: rom
      labels:
        vendor: 389_ds
    tty: true
    stdin_open: true
    ports:
      - 3389:389
      - 3636:636
    restart: on-failure
    healthcheck:
      test: "curl -u 'cn=Directory Manager:topsecret' ldap://127.0.0.1/dc=rom,dc=ldap || exit 1"
    networks:
      - rom-ldap-network



  opendj:
    container_name: opendj
    build:
      context: ./opendj
      args:
        version: 4.4.9
        instance: rom
      labels:
        vendor: open_dj
    tty: true
    stdin_open: true
    ports:
      - 4389:389
      - 4636:636
    restart: on-failure
    healthcheck:
      test: "curl ldap://127.0.0.1/dc=rom,dc=ldap || exit 1"
    networks:
      - rom-ldap-network
