---
  # :host:            127.0.0.1
  :port:            10389
  :base:            ou=users,dc=example,dc=com
  :admin:           uid=admin,ou=system
  :password:        secret
  # :force_no_page:   false
  :verbose:         true
  # :connect_timeout: 5
  # :instrumentation_service:
