source 'https://rubygems.org'

gem 'ldap-ber', git: 'bb:ldap-ber', branch: 'develop'
gem 'pry-byebug'
gem 'rom-changeset'
# bundle config local.rom-ldap ~/Code/rom-ldap
gem 'rom-ldap', git: 'bb:rom-ldap', branch: 'develop'
gem 'rom-repository'
